services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: itinerary-api
    environment:
      APP_ENV: docker
      DATA_PATH: /srv/app/data/sample_pois.json
      OSRM_BASE_URL: http://osrm:5000
      REDIS_URL: redis://redis:6379/0
      REROUTE_COOLDOWN_SECONDS: 180
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgis
      - osrm
    volumes:
      - ./data:/srv/app/data:ro
    networks:
      - travel-network

  postgis:
    image: postgis/postgis:16-3.4
    container_name: itinerary-postgis
    environment:
      POSTGRES_DB: itinerary
      POSTGRES_USER: itinerary
      POSTGRES_PASSWORD: itinerary
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
    networks:
      - travel-network

  redis:
    image: redis:7-alpine
    container_name: itinerary-redis
    ports:
      - "6379:6379"
    networks:
      - travel-network

  osrm:
    image: osrm/osrm-backend:latest
    container_name: itinerary-osrm
    # [FACT] Đổi thuật toán sang CH để bảo vệ KPI Matrix < 50ms
    command: osrm-routed --algorithm ch /data/vietnam-latest.osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    networks:
      - travel-network
    deploy:
      resources:
        limits:
          # [FACT] Chặn giới hạn RAM để chống crash máy Windows 8GB của Dev 2
          memory: 1.5G 

networks:
  travel-network:
    driver: bridge

volumes:
  postgis-data:
