// AUTO-GENERATED by code_generator.js — DO NOT EDIT MANUALLY
import React from 'react';
import { AbsoluteFill, Audio, interpolate, staticFile, useCurrentFrame } from 'remotion';
import { Scene1, Scene2, Scene3, Scene4, Scene5, Scene6, Scene7, Scene8, Scene9, Scene10 } from './Scenes';

export const AutoVideo: React.FC = () => {
  const frame = useCurrentFrame();
  const vignettePulse = interpolate(Math.sin(frame / 60), [-1, 1], [0.3, 0.5]);

  return (
    <AbsoluteFill style={{ backgroundColor: '#000000', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
      <Audio src={staticFile('vo_full.mp3')} />
      <div style={{ position: 'absolute', inset: 0, background: `radial-gradient(circle at center, transparent 40%, rgba(0,0,0,${vignettePulse}) 100%)`, pointerEvents: 'none', zIndex: 100 }} />
      <Scene1 />
      <Scene2 />
      <Scene3 />
      <Scene4 />
      <Scene5 />
      <Scene6 />
      <Scene7 />
      <Scene8 />
      <Scene9 />
      <Scene10 />
    </AbsoluteFill>
  );
};
