// AUTO-GENERATED by code_generator.js — DO NOT EDIT MANUALLY
import React from 'react';
import { DarkBeat, BigTextReveal } from '../templates';


export const Scene1: React.FC = () => (
  <DarkBeat
        startFrame={3}
        endFrame={183}
        conceptWord="MẮC KẸT"
        supportText="TRONG VÒNG LẶP"
        conceptColor="#CC0000"
        headType="syringe"
        posture="slouched"
  />
);

export const Scene2: React.FC = () => (
  <DarkBeat
        startFrame={182}
        endFrame={347}
        conceptWord="ẢO TƯỞNG"
        supportText="CHỈ TIÊU THỤ"
        conceptColor="#CC0000"
        headType="mask"
        posture="slouched"
  />
);

export const Scene3: React.FC = () => (
  <DarkBeat
        startFrame={347}
        endFrame={777}
        conceptWord="QUÁ TẢI"
        supportText="THÔNG TIN LIÊN TỤC"
        conceptColor="#CC0000"
        headType="gear"
        posture="slouched"
  />
);

export const Scene4: React.FC = () => (
  <DarkBeat
        startFrame={777}
        endFrame={832}
        conceptWord="KẾT QUẢ?"
        supportText="SAU TẤT CẢ"
        conceptColor="#F5E500"
        headType="wrench"
        posture="slouched"
  />
);

export const Scene5: React.FC = () => (
  <DarkBeat
        startFrame={832}
        endFrame={1052}
        conceptWord="MẤT PHƯƠNG HƯỚNG"
        supportText="LÃNG PHÍ THỜI GIAN"
        conceptColor="#CC0000"
        headType="cracked"
        posture="slouched"
  />
);

export const Scene6: React.FC = () => (
  <DarkBeat
        startFrame={1052}
        endFrame={1251}
        conceptWord="BẾ TẮC"
        supportText="KIỆT SỨC & HỖN LOẠN"
        conceptColor="#CC0000"
        headType="cracked"
        posture="slouched"
  />
);

export const Scene7: React.FC = () => (
  <DarkBeat
        startFrame={1251}
        endFrame={1529}
        conceptWord="HOÀI NGHI"
        supportText="TỰ VẤN BẢN THÂN"
        conceptColor="#CC0000"
        headType="cracked"
        posture="slouched"
  />
);

export const Scene8: React.FC = () => (
  <BigTextReveal
        startFrame={1529}
        endFrame={1800}
        subtitle="KHÔNG HỀ"
        mainText="VẤN ĐỀ KHÔNG PHẢI BẠN"
        accentColor="#F5E500"
  />
);

export const Scene9: React.FC = () => (
  <DarkBeat
        startFrame={1800}
        endFrame={1963}
        conceptWord="KHÔNG PHÙ HỢP"
        supportText="LỜI KHUYÊN CHUNG CHUNG"
        conceptColor="#F5E500"
        headType="wrench"
        posture="upright"
  />
);

export const Scene10: React.FC = () => (
  <DarkBeat
        startFrame={1963}
        endFrame={2113}
        conceptWord="TRỐN TRÁNH"
        supportText="ĐỂ KHÔNG PHẢI SỐNG"
        conceptColor="#F5E500"
        headType="mask"
        posture="upright"
  />
);
