/**
 * code_generator.js
 * 
 * Reads video_plan.json → Generates src/AutoVideo/Scenes.tsx and src/AutoVideo/index.tsx
 * This is the CRITICAL missing piece that connects the JSON plan to actual Remotion code.
 * 
 * Usage: node tools/code_generator.js
 */

const fs = require('fs');
const path = require('path');

const PLAN_PATH = path.join(__dirname, '../src/AutoVideo/video_plan.json');
const SCENES_OUTPUT = path.join(__dirname, '../src/AutoVideo/Scenes.tsx');
const INDEX_OUTPUT = path.join(__dirname, '../src/AutoVideo/index.tsx');

function generatePropsCode(scene) {
  const props = [];
  const p = scene.params || {};

  // Fallback: ensure startFrame/endFrame are always valid numbers
  const startFrame = typeof scene.startFrame === 'number' ? scene.startFrame : 0;
  const endFrame = typeof scene.endFrame === 'number' ? scene.endFrame : startFrame + 150;

  props.push(`startFrame={${startFrame}}`);
  props.push(`endFrame={${endFrame}}`);

  switch(scene.template) {
    case 'BigTextReveal':
      if (p.subtitle) props.push(`subtitle="${p.subtitle}"`);
      props.push(`mainText="${p.mainText || p.text || ''}"`);
      if (p.accentColor) props.push(`accentColor="${p.accentColor}"`);
      break;

    case 'KeywordCards':
      if (p.subtitle) props.push(`subtitle="${p.subtitle}"`);
      props.push(`keywords={${JSON.stringify(p.keywords || [])}}`);
      break;

    case 'SequentialLines':
      props.push(`lines={${JSON.stringify(p.lines || [])}}`);
      if (p.glowLastLine !== undefined) props.push(`glowLastLine={${p.glowLastLine}}`);
      break;

    case 'ImpactWord':
      props.push(`word="${p.word || p.text || ''}"`);
      if (p.color) props.push(`color="${p.color}"`);
      if (p.flash !== undefined) props.push(`flash={${p.flash}}`);
      break;

    case 'CounterReveal':
      props.push(`targetNumber={${p.targetNumber || 0}}`);
      props.push(`label="${p.label || ''}"`);
      if (p.subtitle1) props.push(`subtitle1="${p.subtitle1}"`);
      if (p.subtitle2) props.push(`subtitle2="${p.subtitle2}"`);
      if (p.highlightWord) props.push(`highlightWord="${p.highlightWord}"`);
      if (p.color) props.push(`color="${p.color}"`);
      if (p.strikethroughText) props.push(`strikethroughText="${p.strikethroughText}"`);
      break;

    case 'TriedItAllList':
      props.push(`items={${JSON.stringify(p.items || [])}}`);
      if (p.lastItemAccent !== undefined) props.push(`lastItemAccent={${p.lastItemAccent}}`);
      if (p.accentColor) props.push(`accentColor="${p.accentColor}"`);
      break;

    case 'DarkBeat':
      if (p.conceptWord) props.push(`conceptWord="${p.conceptWord}"`);
      if (p.supportText) props.push(`supportText="${p.supportText}"`);
      if (p.conceptColor) props.push(`conceptColor="${p.conceptColor}"`);
      if (p.headType) props.push(`headType="${p.headType}"`);
      if (p.posture) props.push(`posture="${p.posture}"`);
      break;

    default:
      console.warn(`⚠️ Unknown template: ${scene.template}`);
  }

  return props.join('\n        ');
}

function generate() {
  console.log('🔨 Code Generator: Reading video_plan.json...');

  if (!fs.existsSync(PLAN_PATH)) {
    console.error('❌ video_plan.json not found at:', PLAN_PATH);
    process.exit(1);
  }

  const plan = JSON.parse(fs.readFileSync(PLAN_PATH, 'utf-8'));
  const scenes = plan.scenes || [];

  // Collect unique template names
  const usedTemplates = [...new Set(scenes.map(s => s.template))];

  // Generate Scenes.tsx
  const scenesCode = `// AUTO-GENERATED by code_generator.js — DO NOT EDIT MANUALLY
import React from 'react';
import { ${usedTemplates.join(', ')} } from '../templates';

${scenes.map((scene, i) => `
export const Scene${i + 1}: React.FC = () => (
  <${scene.template}
        ${generatePropsCode(scene)}
  />
);`).join('\n')}
`;

  fs.writeFileSync(SCENES_OUTPUT, scenesCode);
  console.log(`✅ Generated: ${SCENES_OUTPUT} (${scenes.length} scenes)`);

  // Generate index.tsx (Composition)
  const sceneImports = scenes.map((_, i) => `Scene${i + 1}`).join(', ');
  const palette = plan.palette || { bg: '#0a0a0a' };

  const indexCode = `// AUTO-GENERATED by code_generator.js — DO NOT EDIT MANUALLY
import React from 'react';
import { AbsoluteFill, Audio, interpolate, staticFile, useCurrentFrame } from 'remotion';
import { ${sceneImports} } from './Scenes';

export const AutoVideo: React.FC = () => {
  const frame = useCurrentFrame();
  const vignettePulse = interpolate(Math.sin(frame / 60), [-1, 1], [0.3, 0.5]);

  return (
    <AbsoluteFill style={{ backgroundColor: '${palette.bg || '#0a0a0a'}', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
      <Audio src={staticFile('vo_full.mp3')} />
      <div style={{ position: 'absolute', inset: 0, background: \`radial-gradient(circle at center, transparent 40%, rgba(0,0,0,\${vignettePulse}) 100%)\`, pointerEvents: 'none', zIndex: 100 }} />
${scenes.map((_, i) => `      <Scene${i + 1} />`).join('\n')}
    </AbsoluteFill>
  );
};
`;

  fs.writeFileSync(INDEX_OUTPUT, indexCode);
  console.log(`✅ Generated: ${INDEX_OUTPUT}`);
  console.log(`📊 Total frames: ${plan.totalFrames || 'unknown'}`);
}

generate();
